spring.application.name=market-data-service
server.port=8080
# Timezone settings

# === MYSQL DATABASE (Primary) ===
spring.datasource.primary.jdbc-url=jdbc:mysql://127.0.0.1:3306/ticmi_cacp?allowZeroDateTime=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.primary.username=root
spring.datasource.primary.password=
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

# === MYSQL DATABASE (Secondary) ===
spring.datasource.secondary.jdbc-url=jdbc:mysql://127.0.0.1:3306/datafeedbei2?allowZeroDateTime=true&useSSL=false&serverTimezone=UTC
spring.datasource.secondary.username=root
spring.datasource.secondary.password=
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

# === MYSQL DATABASE (Secondary) ===
spring.datasource.tertiary.jdbc-url=jdbc:mysql://127.0.0.1:3306/idxopenapi?allowZeroDateTime=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.tertiary.username=root
spring.datasource.tertiary.password=
spring.datasource.tertiary.driver-class-name=com.mysql.cj.jdbc.Driver

# === FEATURES CONFIG ===
# iqp.source.enabled=false
WebTrading.DataEnableCACP=true
# WebTrading.CACP_IDXDNA=true
# WebTrading.DataEnableHistorical=true

# === CACHING CONFIG ===
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=12h
spring.cache.cache-names=fundamentals-en,fundamentals-id,corporateActionCache

# Logging configuration
logging.level.root=WARN
logging.level.com.spring.idxMobile=WARN
logging.level.com.marketdata=DEBUG
logging.level.org.springframework.cache=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n
logging.file.name=logs/market-data-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n


